apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcheck-api
  namespace: bcheck-ns
  labels:
    app: bcheck-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bcheck-api
  strategy: {}
  template:
    metadata:
      labels:
        app: bcheck-api
    spec:
      containers:
        - name: bcheck-api
          image: AWS_ECR_URI
          ports:
            - containerPort: 7777
          resources: {}