version: 0.2

env:
  variables:
    SPRING_PROFILE: "dev"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 160270626841.dkr.ecr.ap-northeast-2.amazonaws.com
      - REPOSITORY_URI=160270626841.dkr.ecr.ap-northeast-2.amazonaws.com/bcheck-api-docker-test-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - IMAGE_URI="${REPOSITORY_URI}:latest"
  build:
    commands:
      - chmod +x ./gradlew
      - echo unit testing ...
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE} ./gradlew test
      - echo make jar ...
      - ./gradlew assemble
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile -t $REPOSITORY_URI:latest --build-arg JAR_FILE=build/libs/bcheck-api-docker-test-0.0.1-SNAPSHOT.jar .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - printf '[{"name":"bcheck-api-docker-test", "imageUri":"%s"}]' "$IMAGE_URI" > imagedefinitions.json
      - DATE=`date`
      - echo Build completed on $DATE
artifacts:
  files: imagedefinitions.json
cache:
  paths:
    - '/root/.gradle/**/*'